---
title: |
 | Taller: Lab 8: Actividad inicial experimentos de encuesta
output:
  html_document:
    toc: true
    number_sections: true
    toc_depth: 3
    toc_float: true
    theme: spacelab
    highlight: tango
urlcolor: BrickRed
lang : es-AR
header-includes: \usepackage[spanish]{babel}
                 \usepackage{graphicx}
                 \usepackage{subfig}                 

---

***
```{r setup, include = FALSE}

knitr::opts_chunk$set(fig.align = "center", eval=TRUE, tidy.opts=list(width.cutoff=60), tidy=TRUE, cache=TRUE)

paquetes <- c('readstata13', 'dplyr', 'data.table', 'ggplot2', 'tidyverse')
suppressPackageStartupMessages(sapply(paquetes,require,character.only=TRUE))


```


***

Cargamos la librería:

```{r, tidy=TRUE}
# install.packages("gsheet")
library(gsheet)
# install.packages("ri2")
library(ri2)
# install.packages("tidyverse")
library(tidyverse)
```


# Datos 

Importamos y limpiamos los datos:

```{r, tidy=TRUE}
dat <- rio::import("https://docs.google.com/spreadsheets/d/1SKWljS1EeNkAV5V0NZUwrKOu3LQFILVMB37xfTxyrPM/edit#gid=778386445")
# dat <- read.delim("activity01.tsv")
dat

dat[["Guess"]] <- as.numeric(gsub("[[:punct:]]", "", dat[["Guess"]]))
```

Análisis del experimento con OLS:

```{r, tidy=TRUE}
# plot
plot(Guess~as.factor(Group), dat)

## t-test
t.test(Guess ~ Group, data = dat) # se asumen varianza desigual
t.test(Guess ~ Group, data = dat, var.equal = TRUE)

## Regresion MCO
s <- summary(m <- lm(Guess ~ Group, data = dat))

```

Análisis del experimento con RI:

```{r, tidy=TRUE}
#Crear Z - nueva variable de Tratamiento
dat <- mutate(dat, Z = case_when(
    Group == "Group 1" ~ 0,
    TRUE ~ 1)
)

# declarar el procedimiento de aleatorización
declaration <- randomizr::declare_ra(N = 153, m = 2)

declaration

# Prueba a dos colas
ri2_out <- conduct_ri(
    formula = Guess ~ Z,
    declaration = declaration,
    sharp_hypothesis = 0,
    data = dat,
    sims = 1000,
    p = "two-tailed"
)

summary(ri2_out)

plot(ri2_out)

# Prueba a una cola
ri2_out <- conduct_ri(
    formula = Guess ~ Z,
    declaration = declaration,
    sharp_hypothesis = 0,
    data = dat,
    sims = 1000,
    p = "upper"
)

summary(ri2_out)

plot(ri2_out)

```

# Datos Estudiantes Uruguayos

Importamos y limpiamos los datos:

```{r, tidy=TRUE}
library(gsheet)
dat <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1JFhZ3vrgMMBWy7Ln6vfgaeYIgeg_TgEh6ah2ztyGaOk/edit?usp=sharing")
# rename variables
names(dat) <- c('Timestamp', 'Group', 'Guess')
dat
```

Análisis del experimento con RI:

```{r, tidy=TRUE}
#Crear Z - nueva variable de Tratamiento
dat <- mutate(dat, Z = case_when(
    Group == "Group 1" ~ 0,
    TRUE ~ 1)
)

# declarar el procedimiento de aleatorización
declaration <- randomizr::declare_ra(N = 9, m = 2)

declaration

# Prueba a dos colas
ri2_out <- conduct_ri(
    formula = Guess ~ Z,
    declaration = declaration,
    sharp_hypothesis = 0,
    data = dat,
    sims = 1000,
    p = "two-tailed"
)

summary(ri2_out)

plot(ri2_out)

# Prueba a una cola
ri2_out <- conduct_ri(
    formula = Guess ~ Z,
    declaration = declaration,
    sharp_hypothesis = 0,
    data = dat,
    sims = 1000,
    p = "upper"
)

summary(ri2_out)

plot(ri2_out)

```

